apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-default-app-2023-10-16-1697442398799"

  links:
    - url: https://github.com/RohanAwasthi/aws-elasticbeanstalk-20231016074638
      title: "my-default-app-2023-10-16-1697442398799"
      icon: code

  labels:
    system: web-apps
    trackid: "aws-elasticbeanstalk-20231016074638"
    environmentname: my-java-env

  tags:
    - java
    - aws
    - "applicationtype-webapplication"

  annotations:
    # add elastic beanstalk annotation
    jenkins.io/github-folder: 'custom-actions/tf-my-default-app-2023-10-16-1697442398799'
    github.com/project-slug: RohanAwasthi/aws-elasticbeanstalk-20231016074638
    backstage.io/techdocs-ref: dir:.
    backstage.io/linguist: https://github.com/ItRachii/spring-boot-ebs
    sonarqube.org/project-key: 'demo-app/aws-elb-java'

spec:
  type: service
  lifecycle: experimental
  system: elasticbeanstalk
  owner: "group:default/ey"
